### ISSUE TITLE
Type slider is not available, yet.

### ISSUE THREAD

**Issue by DutchmanNL** [TA2k/ioBroker.iot#2]
```
Cannot auto convert hm-rpc.1.00111A499156F8.4. Type slider is not available, yet. If you need the state please add him manually
```

**Comment by TA2k** [comment]
I think this slider devices are virtual and not needed for google home?

**Comment by DutchmanNL** [comment]
> I think this slider devices are virtual and not needed for google home?

hmm not sure, it was automatically created for an HM-IP device (HmIP-BROLL)

i manual created the device and now it works fine : 

<img width="1236" alt="Schermafbeelding 2019-09-02 om 21 44 23" src="https://user-images.githubusercontent.com/7318445/64131731-d7419c80-cdca-11e9-9ead-becea190af3b.png">

**Comment by TA2k** [comment]
I added slider as auto processed as blinds
